### PR TITLE
Fixed email validation in Signup and login  component and integrated …

### PR DESCRIPTION
**Pull request by AkhileshNandanwar**
…snackbar to display feedback messages

### CODE REVIEW

**Comment by AkhileshNandanwar** [comment]
vercel deployment is failing otherwise the changes in login and signup as mentioned are done correctly and tested multiple times

**Comment by RutikKulkarni** [comment]
Hi Akhilesh Nandanwar,

I noticed that you made changes to the frontend file for validation purposes. However, validation should be implemented in the backend, as indicated by the backend label on this issue.

Additionally, it appears that you have pushed the `node_modules` folder to the repository. As a best practice, please remember not to push `node_modules` to the Git repository. 

And because of this `node_modules` folder, vercel deployment is failing.

For this issue, please sync the repository first and then submit a new pull request.

Thank you.

**Comment by AkhileshNandanwar** [comment]
well as you had said,i implemented the changes in backend..so needed a help about how should i check it is it properly implementing or not

**Comment by RutikKulkarni** [comment]
> well as you had said,i implemented the changes in backend..so needed a help about how should i check it is it properly implementing or not

Hi, the issue has been resolved this morning. Please sync the fork and verify. Feel free to tackle other open issues. Thanks!

**Comment by RutikKulkarni** [comment]
I'll close this pull request now

**Pull request closed without merging**
